version: "3.9"

services:
  db:
    image: postgres:14
    container_name: aegiscare-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aegiscare
      POSTGRES_PASSWORD: aegiscare
      POSTGRES_DB: aegiscare
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
