apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegiscare-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aegiscare
  template:
    metadata:
      labels:
        app: aegiscare
    spec:
      containers:
        - name: backend
          image: aegiscare:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
            - name: HOSTNAME  # inject it as an environment variable using a Kubernetes Downward API:
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
