apiVersion: v1
kind: Service
metadata:
  name: aegiscare-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: aegiscare      # Must match your Deployment's pod labels
  ports:
    - protocol: TCP
      port: 8000          # External port to access
      targetPort: 8000  # FastAPI internal container port
      nodePort: 30080   # Port to access the service externally